export const endpoints = {
  customers: {
    list: "/v1/customers",
    getById: (id: number) => `/v1/customers/${id}`,
    getOrders: (id: number) => `/v1/customers/${id}/orders`,
    create: "/v1/customers",
    update: (id: number) => `/v1/customers/${id}`,
    delete: (id: number) => `/v1/customers/${id}`,
  },
  salesOrders: {
    list: "/v1/sales-orders",
    getById: (id: number) => `/v1/sales-orders/${id}`,
    create: "/v1/sales-orders",
    update: (id: number) => `/v1/sales-orders/${id}`,
    delete: (id: number) => `/v1/sales-orders/${id}`,
    confirm: (id: number) => `/v1/sales-orders/${id}/confirm`,
    ship: (id: number) => `/v1/sales-orders/${id}/ship`,
    cancel: (id: number) => `/v1/sales-orders/${id}/cancel`,
  },
  products: {
    list: "/v1/products",
    getById: (id: number) => `/v1/products/${id}`,
    lowStock: "/v1/products/low-stock",
  },
  inventory: {
    list: "/v1/products",
    getById: (id: number) => `/v1/products/${id}`,
    create: "/v1/products",
    update: (id: number) => `/v1/products/${id}`,
    delete: (id: number) => `/v1/products/${id}`,
  },
  categories: {
    list: "/v1/categories",
    getById: (id: number) => `/v1/categories/${id}`,
    create: "/v1/categories",
    update: (id: number) => `/v1/categories/${id}`,
    delete: (id: number) => `/v1/categories/${id}`,
  },
  suppliers: {
    list: "/v1/suppliers",
    getById: (id: number) => `/v1/suppliers/${id}`,
    create: "/v1/suppliers",
    update: (id: number) => `/v1/suppliers/${id}`,
    delete: (id: number) => `/v1/suppliers/${id}`,
  },
  purchaseOrders: {
    list: "/v1/purchase-orders",
    getById: (id: number) => `/v1/purchase-orders/${id}`,
    create: "/v1/purchase-orders",
    update: (id: number) => `/v1/purchase-orders/${id}`,
    delete: (id: number) => `/v1/purchase-orders/${id}`,
    receive: (id: number) => `/v1/purchase-orders/${id}/receive`,
    cancel: (id: number) => `/v1/purchase-orders/${id}/cancel`,
  },
  invoices: {
    list: "/v1/invoices",
    getById: (id: number) => `/v1/invoices/${id}`,
    create: "/v1/invoices",
    update: (id: number) => `/v1/invoices/${id}`,
    delete: (id: number) => `/v1/invoices/${id}`,
    send: (id: number) => `/v1/invoices/${id}/send`,
    cancel: (id: number) => `/v1/invoices/${id}/cancel`,
    addPayment: (id: number) => `/v1/invoices/${id}/payments`,
  },
  journal: {
    list: "/v1/journal-entries",
    getById: (id: number) => `/v1/journal-entries/${id}`,
    create: "/v1/journal-entries",
    post: (id: number) => `/v1/journal-entries/${id}/post`,
    reverse: (id: number) => `/v1/journal-entries/${id}/reverse`,
  },
  accounts: {
    list: "/v1/accounts",
    getById: (id: number) => `/v1/accounts/${id}`,
    create: "/v1/accounts",
    update: (id: number) => `/v1/accounts/${id}`,
    delete: (id: number) => `/v1/accounts/${id}`,
  },
  employees: {
    list: "/v1/employees",
    getById: (id: number) => `/v1/employees/${id}`,
    getAttendance: (id: number) => `/v1/employees/${id}/attendance`,
    create: "/v1/employees",
    update: (id: number) => `/v1/employees/${id}`,
    delete: (id: number) => `/v1/employees/${id}`,
  },
  attendance: {
    clockIn: "/v1/attendance/clock-in",
    clockOut: "/v1/attendance/clock-out",
    list: "/v1/attendance",
  },
  leave: {
    list: "/v1/leave-requests",
    getById: (id: number) => `/v1/leave-requests/${id}`,
    create: "/v1/leave-requests",
    approve: (id: number) => `/v1/leave-requests/${id}/approve`,
    reject: (id: number) => `/v1/leave-requests/${id}/reject`,
    balances: "/v1/leave-balances",
  },
  users: {
    list: "/v1/users",
    getById: (id: number) => `/v1/users/${id}`,
    create: "/v1/users",
    update: (id: number) => `/v1/users/${id}`,
    delete: (id: number) => `/v1/users/${id}`,
  },
  dashboard: {
    stats: "/v1/dashboard/stats",
  },
};
